</div>

<div id="chapter-5" class="chapter">
<hr class="chap">

## CHAPTER V.<br>THE PROBLEMS OF LEADERSHIP.

[In all the tangles of our awakening race consciousness there
are perhaps none more knotty than the tangles relating to leadership. 
Leadership among Negro Americans, as among other people, 
means the direction of a group’s activities, whether by
precept, example or compulsion. But, in our case, there is involved 
a strikingly new element. Should the leading of our
group in any sense be the product of our group’s consciousness
or of a consciousness originating from outside that group? What
the new Negro thinks on the problem of “outside interference”
in the leadership of his group is expressed in the first and sixth
editorials of this chapter, one of which appeared in *The Voice*
and the other in *The Negro World*.

“A Tender Point” formulates one part of the problem of
leadership which is seldom touched upon by Negro Americans
who characteristically avoid any public presentation of a thing
about which they will talk interminably in private; namely, the
claim advanced, explicitly and implicitly, by Negroids of mixed
blood to be considered the natural leaders of Negro activities on
the ground of some alleged “superiority” inherent in their white
blood.

“The Descent of Du Bois” was written at the request of Major
Loving of the Intelligence Department of the Army at the time
when Dr. Du Bois, the editor of *The Crisis*, was being preened
for a desk captaincy at Washington. Major Loving solicited a
summary of the situation from me as one of those “radicals”
qualified to furnish such a summary. This he incorporated in his
report to his superiors in Washington, and this I published a week
later in *The Voice* of July 25, 1918, as an editorial without
changing a single word. I was informed by Major Loving that
this editorial was one of the main causes of the government’s
change of intention as regards the Du Bois captaincy. Since
that time Dr. Du Bois’s white friends have been fervidly ignoring 
the occurrence and the consequent collapse of his leadership.
“When the Blind Lead” was written as a reminder to the souls
of black folks that “while it is as easy as eggs for a leader to
fall off the fence, it is devilishly difficult to boost him up again.”
“Just Crabs” was a delightful inspiration in the course of
defending, not Mr. Garvey personally, but the principles of the
New Negro Manhood Movement, a portion of which had been
incorporated by him and his followers of the U.N.I.A. and
A.C. L. It was the opening gun of the defense, of which some
other salvos were given in the serial satire of The Crab Barrel&mdash;which
 I have been kind enough to omit from this record. This
controversy also gave rise to the three first editorials of
chapter 6.]

### Our Professional “Friends”

This country of ours has produced many curious lines
of endeavor, not the least curious of which is the business
known as “being the Negro’s friend.” It was first invented
by politicians, but was taken up later by “good” men, sixper-cent
 philanthropists, millionaire believers in “industrial
education,” benevolent newspapers like the *Evening Post*,
and a host of smaller fry of the “superior race.” Just at
this time the business is being worked to death, and we
wish to contribute our mite toward the killing-by showing 
what it means.

The first great “friend” of the Negro was the Southern
politician, Henry Clay, who, in the first half of the nineteenth
century organized the American Colonization
Society. This society befriended the “free men of color”
by raising funds to ship them away to Liberia, which was
accepted by many free Negroes as a high proof of the
white man’s “friendship.” But Frederick Douglass,
William Still, James McCune Smith, Martin R. Delaney,
and other wide-awake Negroes were able to show (by
transcripts of its proceedings) that its real purpose was
to get rid of the free Negroes because, so long as they
continued to live here, their freedom was an inducement
to the slaves to run away from slavery, and their accomplishments 
demonstrated to all white people that the
Negro (contrary to the claims of the slave-holders) was
capable of a higher human destiny than that of being chattels&mdash;and
this was helping to make American slavery
odious in the eyes of the civilized world.

Since that time the dismal farce of “friendship” has
been played many times, by politicians, millionaires and
their editorial adherents, who have been profuse in giving
good advice to the Negro people. They have advised them
to “go slow,” that “Rome was not built in a day,” and
that “half a loaf is better than no bread,” that “respect
could not be demanded,” and, in a thousand different
ways have advised them that if they would only follow
the counsels of “the good white people” who really had
their interests at heart, instead of following their own
counsels (as the Irish and the Jews do), all would yet be
well. Many Negroes who have a wish-bone where their
back-bone ought to be have been doing this. It was as a
representative of this class that Mitchell’s man, Mr. Fred
R. Moore, the editor of *The Age*, spoke, when in July he
gave utterance to the owlish reflection that,

> The Negro race is afflicted with many individuals whose wagging
tongues are apt to lead them into indiscreet utterances that reflect
upon the whole race. ... The unruly tongues should not be
allowed to alienate public sympathy from the cause of the
oppressed.

It was as a fairly good representative of the class of
“good white friends of the colored people” that Miss Mary
White Ovington, the chairman of the New York Branch
of the National Association for the Advancement of
Colored People, sent to *The Voice* the following bossy
and dictatorial note:

<div class="letter">
<p>My dear Mr. Harrison,<p>
<p>I don’t see any reason for another organization, or another paper. If you printed straight socialism it might be different.<p>
<p>Yours truly,<p>
<p class="signature">MARY W. OVINGTON.<p>
</div>

These “good white people” must really forgive us for
insisting that we are not children, and that, while we
want all the friends we can get, we need no benevolent
dictators. It is we, and not they, who must shape Negro
policies. If they want to help in carrying them out we
will appreciate their help.

Just now the white people even in the South&mdash;have
felt the pressure of the new Negro’s manhood demands,
in spite of the fact that backward-looking Negroes like
*The Age*’s editor condemn the inflexible spirit of these
demands. All over the South, the white papers, scared
by the exodus of Negro laborers who are tired of begging
for justice overdue, are saying that we are right, and
friendlier legislation has begun to appear on Southern
statute books. Mr. Mencken and other Southern writers
are saying that the Negro is demanding, and that the
South had better accede to his just demands, as it is only
a matter of time when he will be in position to enforce
them. One should think, then, that those who have been
parading as our professional friends would be in the van
of this manhood movement. But the movement seems
to have left them in the rear. Now, that we are demanding 
the whole loaf, they are begging for half, and are
angry at us for going further than they think “nice.”

It was the N.A.A.C.P. which was urging us to compromise
our manhood by begging eagerly for “Jim Crow”
training camps. And the same group is asking, in the
November *Crisis*, that we put a collective power-of-attorney 
into their hand and leave it to them to shape our national 
destiny. The N.A.A.C.P. has done much good
work for Negroes&mdash;splendid work&mdash;in fighting lynching
and segregation. For that we owe it more gratitude and
good will than we owe to the entire Republican party
for the last sixty years of its existence. But we cannot,
even in this case, abdicate our right to shape more radical
policies for ourselves. It was the realization of the need
for a more radical policy than that of the N.A.A.C.P.
that called into being the Liberty League of Negro
Americans. And the N.A.A.C.P., as mother, must forgive 
its offspring for forging farther ahead.

Then, there is the case of the New York *Evening Post*,
of which Mr. Villard is owner. This paper was known
far and wide as “a friend to Negroes.” But its friendship
has given way to indifference and worse. In the good old
days every lynching received editorial condemnation. But
the three great lynchings this year which preceded East
St. Louis found no editorial of condemnation in the *Post*.
It was more than luke-warm then. But, alack and alas!
As soon as the Negro soldiers in Houston, goaded to
retaliation by gross indignities, did some shooting on
their own account, the *Evening Post*, which had no condemnation 
of the conduct of the lynchers, joined the
chorus of those who were screaming for “punishment”
and death. Here is its brief editorial on August 25th:

> As no provocation could justify the crimes committed by
mutinous Negro soldiers at Houston, Texas, so no condemnation
of their conduct can be too severe. It may be that the local
authorities were not wholly blameless, and that the commanding
officers were at fault in not foreseeing the trouble and taking
steps to guard against it. But nothing can really palliate the
offence of the soldiers. They were false to their uniform; they
were false to their race. In one sense, this is the most deplorable
aspect of the whole riotous outbreak. It will play straight
into the hands of men like Senator Vardaman who have been
saying that it was dangerous to draft colored men into the army.
And the feeling against having colored troops encamped in the
South will be intensified. The grievous harm which they might
do to their own people should have been all along in the minds
of the colored soldiers, and made them doubly circumspect. They
were under special obligation, in addition to their military oath,
to conduct themselves so as not to bring reproach upon the
Negroes as a whole, of whom they were in a sort representative.
Their criminal outrage will tend to make people forget the good
work done by other Negro soldiers. After the rigid investigation
which the War Department has ordered, the men found guilty
should receive the severest punishment. As for the general army
policy affecting colored troops, we are glad to see that Secretary
Baker appears to intend no change in his recent orders.

We ourselves cannot forget that while the question of
whether the *Post’s* editor would get a diplomatic appointment 
(like some other editors) was under consideration
during the first year of Woodrow Wilson’s first administration, 
the *Post* pretended to believe that the President 
didn’t know of the segregation practiced in the government 
departments. The N.A.A.C.P., whose letter
sent out at the time is now before us, pretended to the
same effect.

After viewing these expressions of frightful friendliness 
in our own times, we have reached the conclusion
that the time has come when we should insist on being
our own best friends. We may make mistakes, of course,
but we ought to be allowed to make our own mistakes&mdash;as 
other people are allowed to do. If friendship is to
mean compulsory compromise foisted on us by kindly
white people, or by cultured Negroes whose ideal is the
imitation of the urbane acquiescence of these white
friends, then we had better learn to look a gift horse in
the mouth whenever we get the chance. &mdash;November, 1917.

<hr>

### Shillady Resigns

Mr. John R. Shillady, ex-secretary of the N.A.A.C.P.,
states in his letter of resignation that “I am less confident
than heretofore of the speedy success of the association’s
full program and of the probability of overcoming within
a reasonable period the forces opposed to Negro equality
by the means and methods which are within the association’s 
power to employ.” In this one sentence Mr. Shillady, 
the worker on the inside, puts in suave and serenely
diplomatic phrase the truth which people on the outside
have long ago perceived, namely, that the N.A.A.C.P.
makes a joke of itself when it affects to think that lynching 
and the other evils which beset the Negro in the South
can be abolished by simple publicity. The great weakness
of the National Association for the Advancement of
Colored People has been and is that, whereas it aims to
secure certain results by affecting the minds of white people 
and making them friendly to it, it has no control over
these minds and has absolutely no answer to the question,
“What steps do you propose to take if these minds at
which you are aiming remain unaffected? What do you
propose to do to secure life and liberty for the Negro if
the white Southerner persists, as he has persisted for sixty
years, in refusing to grant guarantees of life and liberty?”
The N.A.A.C.P. has done some good and worth-while
work as an organization of protest. But the times call for
something more effective than protests addressed to the
other fellow’s consciousness. What is needed at present
is more of the mobilizing of the Negro’s political power,
pocketbook power and intellectual power (which are absolutely 
within the Negro’s own control) to do for the Negro
the things which the Negro needs to have done without
depending upon or waiting for the co-operative action of
white people. This co-operative action, whenever it does
come, is a boon that no Negro, intelligent or unintelligent,
affects to despise. But no Negro of clear vision, whether
he be a leader or not, can afford to predicate the progress
of the Negro upon such co-operative action, because it
may not come.

Mr. Shillady may have seen these things. It is high
time that all Negroes see these things whether their white
professional friends see them or not. &mdash;July, 1920.

<hr>

### Our White Friends

In the good old days when the black man’s highest value
in the white man’s eye was that of an object of benevolence 
especially provided by the Divine mind for calling
out those tender out-pourings of charity which were so
dear to the self-satisfied Caucasian&mdash;in those days the
white men who fraternized with black people could do
so as their guides, philosophers and friends without
incurring any hostility on the part of black folk. Today,
however, the white man who mixes with the black brother
is having a hard time of it. Somehow Ham’s offspring
no longer feels proud of being “taken up” by the progeny
of Japhet. And when the white man insists on mixing in
with him the colored brother will persist in attributing
ulterior motives.

What is the cause of this difference? The answer will
be found only by one who refuses to wear the parochial
blinkers of Anglo-Saxon civilization and sees that the
relations of the white and black race have changed and
are changing all over the world. Such an observer would
note that the most significant fact of the growing race
consciousness is to be found in the inevitable second half
of the word. It isn’t because these darker people are
motivated by race that their present state of mind constitutes 
a danger to Caucasian overlordship. It is because
they have developed consciousness, intelligence, understanding. 
They have learned that the white brother is
perfectly willing to love them&mdash;“in their place.” They
have learned that that place is one in which they are not
to develop brains and initiative, but must furnish the
brawn and muscle whereby the white man’s brain and
initiative can take eternally the products of their brawn
and muscle. There are today many white men who will
befriend the Negro, who will give their dollars to his
comfort and welfare, so long as the idea of what constitutes 
that comfort and welfare comes entirely from the
white man’s mind. Examples like those of Dr. Spingarn
and Mr. E. D. Morel are numerous.

And not for nothing does the black man balk at the
white man’s “mixing in.” For there are spies everywhere
and the *agent provocateur* is abroad in the land. From
Chicago comes the news by way of the Associated Press
(white) that Dr. Jonas, who has always insisted in sticking 
his nose into the Negro peoples’ affairs as their guide,
philosopher and friend, has been forced to confess that he
is a government agent, presumably paid for things which
the government would later suppress. Dr. Jonas is reported 
to have said that he is connected with the British
secret service; but since the second year of the European
war it has been rather difficult for us poor devils to tell
where the American government ended and the British
government began, especially in these matters. In any
case, we have Dr. Jonas’ confession, and all the silly
Negroes who listened approvingly to the senseless allegations 
made by Messrs. Jonas, Gabriel and others of a
standing army of 4,000,000 in Abyssinia and of Japanese-Abyssinian 
diplomatic relations and intentions, must feel
now very foolish about the final result.

How natural it was that Jonas, the white leader, should
have gone scot free, while Redding and his other Negro
dupes are held! How natural that Jonas should be the one
to positively identify Redding as the slayer of the Negro
policeman! And so, once again, that section of the Negro
race that will not follow except where a white man leads
will have to pay that stern penalty whereby Dame Experience 
teaches her dunces. Under the present circumstances 
we, the Negroes of the Western world, do pledge
our allegiance to leaders of our own race, selected by our
own group and supported financially and otherwise exclusively 
by us. Their leadership may be wise or otherwise;
they may make mistakes here and there; nevertheless,
such sins as they may commit will be our sins, and all the
glory that they may achieve will be our glory. We prefer
it so. It may be worth the while of the white men who
desire to be “Our Professional Friends” to take note of
this preference.

<hr>

### A Tender Point

When the convention of turtles assembled on the Grand
Banks of Newfoundland it was found absolutely impossible 
to get a tortoise elected as leader. All turtles, conservative 
and radical, agreed that a land and water
creature, who was half one thing and half another, was not
an ideal choice for leader of a group which lived exclusively 
in the water. Whenever a leader of the Irish has
to be selected by the Irish it is an Irishman who is selected.
No Irishman would be inclined to dispute the fact that
other men, even Englishmen like John Stuart Mill and the
late Keir Hardie, could feel the woes of Ireland as profoundly 
as any Irishman. But they prefer to live up to the
principle of “Safety First.”

These two illustrations are to be taken as a prelude to
an important point which is not often discussed in the
Negro press because all of us&mdash;black, brown and 
parti-colored&mdash;fear 
to offend each other. That point concerns
the biological breed of persons who should be selected
by Negroes as leaders of their race. We risk the offense
this time because efficiency in matters of racial leadership,
as in other matters, should not be too tender to these
points of prejudice when they stand in the way of desirable 
results. For two centuries in America we, the descendants 
of the black Negroes of Africa, have been
told by white men that we cannot and will not amount
to anything except in so far as we first accept the bar
sinister of their mixing with us. Always when white people 
had to select a leader for Negroes they would select
some one who had in his veins the blood of the selectors.
In the good old days when slavery was in flower, it was
those whom Denmark Vesey of Charleston described as
“house niggers” who got the master’s cast-off clothes,
the better scraps of food and culture which fell from
the white man’s table, who were looked upon as the
Talented Tenth of the Negro race. The opportunities of
self-improvement, in so far as they lay within the hand of
the white race, were accorded exclusively to this class of
people who were the left-handed progeny of the white
masters.

Out of this grew a certain attitude on their part
towards the rest of the Negro people which, unfortunately, 
has not yet been outgrown. In Washington, Boston, 
Charleston, New York and Chicago these proponents
of the lily-white idea are prone to erect around their
sacred personalities a high wall of caste, based on the
ground of color. And the black Negroes have heretofore 
worshipped at the altars erected on these walls. One
sees this in the Baptist, Methodist and Episcopal churches,
at the various conventions and in fraternal organizations.
Black people themselves seem to hold the degrading view
that a man who is but half a Negro is twice as worthy
of their respect and support as one who is entirely black.
We have seen in the social life of some of the places mentioned 
how women, undeniably black and undeniably
beautiful, have been shunned and ostracised at public
functions by men who should be presumed to know better. 
We have read the fervid jeremiads of “colored”
men who, when addressing the whites on behalf of some
privilege which they wished to share with them, would
be, in words, as black as the ace of spades, but, when it
came to mixing with “their kind,” they were professional
lily-whites, and we have often had to point out to them
that there is no color prejudice in America&mdash;except among
“colored” people. Those who may be inclined to be angry
at the broaching of this subject are respectfully requested
to ponder that pungent fact.

In this matter white people, even in America, are inclined 
to be more liberal than colored people. If a white
man has no race prejudice, it will be found that he doesn’t
care how black is the Negro friend that he takes to his
home and his bosom. Even these white people who pick
leaders for Negroes have begun in these latter years to
give formal and official expression to this principle. Thus
it was that when the trustees of Tuskegee had to elect
a head of Tuskegee and a putative leader of the Negroes
of America to succeed the late Dr. Washington, they
argued that it was now necessary to select as leader for
the Negro people a man who could not be mistaken by any
one for anything other than a Negro. Therefore, Mr.
Emmett Scott was passed over and Dr. Robert R. Morton
was selected. We are not approving here the results of
that selection, but merely holding up to Negroes the principle 
by which it was governed.

So long as we ourselves acquiesce in the selection of
leaders on the ground of their unlikeness to our racial
type, just so long will we be met by the invincible argument 
that white blood is necessary to make a Negro worth
while. Every Negro who has respect for himself and for
his race will feel, when contemplating such examples as
Toussaint Louverture, Phyllis Wheatley, Paul Laurence
Dunbar and Samuel Ringgold Ward, the thrill of
pride that differs in quality and intensity from
the feeling which he experiences when contemplating
other examples of great Negroes who are not entirely
black. For it is impossible in such cases for the white
men to argue that they owed their greatness of their
prominence to the blood of the white race which was
mingled in their veins. It is a legitimate thrill of pride,
for it gives us a hope nobler than the hope of amalgamation 
whereby, in order to become men, we must lose our
racial identity. It is a subject for sober and serious reflection, 
and it is hoped that sober and serious reflection
will be given to it.

<hr>

### The Descent of Du Bois

In a recent bulletin of the War Department it was
declared that “justifiable grievances” were producing and
had produced “not disloyalty, but an amount of unrest
and bitterness which even the best efforts of their leaders
may not be able always to guide.” This is the simple
truth. The essence of the present situation lies in the
fact that the people whom our white masters have
“recognized” as our leaders (without taking the trouble
to consult us) and those who, by our own selection, had
actually attained to leadership among us are being revaluated 
and, in most cases, rejected.

The most striking instance from the latter class is Dr.
W. E. Du Bois, the editor of the *Crisis*. Du Bois’s case
is the more significant because his former services to his
race have been undoubtedly of a high and courageous
sort. Moreover, the act by which he has brought upon
himself the stormy outburst of disapproval from his race
is one which of itself, would seem to merit no such stern
condemnation. To properly gauge the value and merit
of this disapproval one must view it in the light of its
attendant circumstances and of the situation in which
it arose.

Dr. Du Bois first palpably sinned in his editorial
“Close Ranks” in the July number of the *Crisis*. But
this offense (apart from the trend and general tenor of
the brief editorial) lies in a single sentence: “Let us,
while this war lasts, *forget our special grievances* and
close our ranks, shoulder to shoulder with our white
fellow-citizens and the allied nations that are fighting for
democracy.” From the latter part of the sentence there
is no dissent, so far as we know. The offense lies in
that part of the sentence which ends with the italicized
words. It is felt by all his critics, that Du Bois, of all
Negroes, knows best that our “special grievances” which
the War Department Bulletin describes as “justifiable”
consist of lynching, segregation and disfranchisement,
and that the Negroes of America can not preserve either
their lives, their manhood or their vote (which is their
political life and liberties) with these things in existence.
The doctor’s critics feel that America can not use the
Negro people to any good effect unless they have life,
liberty and manhood assured and guaranteed to them.
Therefore, instead of the war for democracy making
these things less necessary, it makes them more so.

“But,” it may be asked, “why should not these few
words be taken merely as a slip of the pen or a venial
error in logic? Why all this hubbub?” It is because the
so-called leaders of the first-mentioned class have already
established an unsavory reputation by advocating this
same surrender of life, liberty and manhood, masking
their cowardice behind the pillars of war-time sacrifice?
Du Bois’s statement, then, is believed to mark his entrance
into that class, and is accepted as a “surrender” of the
principles which brought him into prominence&mdash;and
which alone kept him there.

Later, when it was learned that Du Bois was being
preened for a berth in the War Department as a captain-assistant 
(adjutant) to Major Spingarn, the words used
by him in the editorial acquired a darker and more
sinister significance. The two things fitted too well together 
as motive and self-interest.

For these reasons Du Bois is regarded much in the
same way as a knight in the middle ages who had had his
armor stripped from him, his arms reversed and his spurs
hacked off. This ruins him as an influential person
among Negroes at this time, alike whether he becomes a
captain or remains an editor.

But the case has its roots much farther back than the
editorial in July’s *Crisis*. Some time ago when it was
learned that the *Crisis* was being investigated by the
government for an alleged seditious utterance a great
clamor went up, although the expression of it was not
open. Negroes who dared to express their thoughts
seemed to think the action tantamount to a declaration
that protests against lynching, segregation and disfranchisement 
were outlawed by the government. But nothing 
was clearly understood until the conference of editors
was called under the assumed auspices of Emmett Scott
and Major Spingarn. Then it began to appear that these
editors had not been called without a purpose. The
desperate ambiguity of the language which they used in
their report in the War Department Bulletin), coupled
with the fact that not one of them, upon his return would
tell the people anything of the proceedings of the conference&mdash;all 
this made the Negroes feel less and less confidence 
in them and their leadership; made them (as
leaders) less effective instruments for the influential
control of the race’s state of mind.

Now Du Bois was one of the most prominent of those
editors “who were called.” The responsibility, therefore,
for a course of counsel which stresses the servile virtues
of acquiescence and subservience falls squarely on his
shoulders. The offer of a captaincy and Du Bois’s firtation 
with that offer following on the heels of these things
seemed, even in the eyes of his associate members of the
N.A.A.C.P. to afford clear proof of that which was
only a suspicion before, viz: that the racial resolution of
the leaders had been tampered with, and that Du Bois
had been privy to something of the sort. The connection
between the successive acts of the drama (May, June,
July) was too clear to admit of any interpretation other
than that of deliberate, cold blooded, purposive planning.
And the connection with Spingarn seemed to suggest that
personal friendships and public faith were not good working 
team-mates.

For the sake of the larger usefulness of Dr. Du Bois
we hope he will be able to show that he can remain as
editor of the *Crisis*; but we fear that it will require a good
deal of explaining. For, our leaders, like Caesar’s wife,
must be above suspicion. &mdash;July, 1918.

<hr>

### When the Blind Lead

In the February issue of the *Crisis* its editor begins a
brief editorial on “Leadership,” with the touching reminder 
that “Many a good cause has been killed by
suspected leadership.” How strikingly do these words
bring back to us Negroes those dark days of 1918! At
that time the editor of the *Crisis* was offering certain
unique formulas of leadership that somehow didn’t
“take.” His “Close Ranks” editorial and the subsequent
slump in the stock of his leadership have again illustrated
the truth long since expressed in Latin: “Descensus
Averni facilis; sed revocare gradus,&mdash;hoc opus est,”
which, being translated, might mean that, while it’s as
easy as eggs for a leader to fall off the fence, it is devilishly 
difficult to boost him up again. In September, 1918,
one could boldly say, “The *Crisis* says, first your Country,
then your Rights!” Today, when the Negro people everywhere 
are responding to Mr. Michael Coulsen’s sentiment
that “it’s Race, not Country, first,” we find the “leader” of
1918 in the position described by Lowell in these words:
“A moultin’ fallen cherubim, ef he should see ye’d snicker,
Thinkin’ he warn’t a suckemstance.”

How fast time flies!

But the gist of Dr. Du Bois’s editorial is the moral
downfall of another great leader. “Woodrow Wilson, in
following a great ideal of world unity, forgot all his
pledges to the German people, forgot all his large words
to Russia, did not hesitate to betray Gompers and his
unions, *and never at any single moment meant to include
in his democracy twelve million of his fellow Americans,
whom he categorically promised “more than mere grudging
justice,” and then allowed 350 of them to be lynched during 
his Presidency.* Under such leadership what cause
could succeed?” He notes that out of the World War,
with the Allies triumphant, have come Britain’s brutal
domination of the seas, her conquest of Persia, Arabia
and Egypt, and her tremendous tyranny imposed on two-thirds 
of Africa.

But we saw these things, as early as 1917, to be the
necessary consequences of the Allies’ success, when the
editor of the *Crisis* was telling his race: “You are not
fighting simply for Europe; you are fighting for the
world.” Was Dr. Du Bois so blind then that he couldn’t
see them? And if he was, is he any less blind today? In
1918 the lynchings were still going on while Dr. Du Bois
was solemnly advising us to “forget our grievances.” Any
one who insisted then on putting such grievances as
lynchings, disfranchisement and segregation in the fore-ground 
was described by the *Crisis*’ editor as seeking “to
turn his country’s tragic predicament to his own personal
gain.” At that time he either believed or pretended to
believe every one of the empty words that flowed from
Woodrow Wilson’s lips, and on the basis of this belief
he was willing to act as a brilliant bellwether to the rest
of the flock. Unfortunately, the flock refused to follow
the lost leader.

“If the blind lead the blind they will both fall into the
ditch.” But in this case those being led were not quite so
blind as those who wanted to lead them by way of captaincies 
in the army. Which was why some captaincies
were not forthcoming. The test of vision in a leader is
the ability to foresee the immediate future, the necessary
consequences of a course of conduct and the dependable
sentiments of those whom he assumes to lead. In all
these things Dr. Du Bois has failed; and neither his ungrateful 
attack on Emmett Scott nor his belated discovery
of Wilsonian hypocrisy will, we fear, enable him to climb
back into the saddle of race leadership. This is a pity,
because he has rendered good service in his day. But that
day is past. The magazine which he edits still remains as
a splendid example of Negro journalism. But the personal 
primacy of its editor has departed, never to return.
Other times, other men; other men, other manners.

Even the Negro people are now insisting that their
leaders shall in thought and moral stamina keep ahead of,
and not behind, them,


<div class="poetry">
<div class="stanza">
<div class="verse leadingquote ">“It takes a mind like Willum’s [fact!) ez big as all outdoors</div>
<div class="verse">To find out thet it looks like rain arter it fairly pours.”</div>
</div>
</div>

The people’s spiritual appetite has changed and they
are no longer enamoured of “brilliant” leaders, whose
chorus is:

<div class="poetry">
<div class="stanza">
<div class="verse leadingquote">“A marciful Providence fashioned us holler</div>
<div class="verse">O’purpose that we might our principles swaller;</div>
<div class="verse">It can hold any quantity on ’em&mdash;the belly can&mdash;</div>
<div class="verse">An’ bring ’em up ready fer use like the pelican.”</div>
</div>
</div>

And this is a change which we commend to the kindly
consideration of all those good white friends who are out
selecting Negro “leaders.” It is a fact which, when carefully
considered, will save them thousands of dollars in
“overhead expense.” The Negro leaders of the future
will be expected not only to begin straight, take a moral
vacation, and then go straight again. They will be expected 
to go straight all the time; to stand by us in war
as well as in peace; not to blow hot and cold with the
same mouth, but “to stand four-square to all the winds
that blow.” &mdash;1920.

<hr>

### Just Crabs

Once upon a time a Greedy Person went rummaging
along the lagoon with a basket and a stick in quest of
Crabs, which he needed for the Home Market. (Now,
this was in the Beginning of Things, Best Beloved.)
These were Land Crabs&mdash;which, you know, are more
luscious than Sea Crabs, being more Primitive and more
full of meat. He dug into their holes with his stick,
routed them out, packed them on their backs in his basket
and took them home. Several trips he made with his
basket and his stick, and all the Crabs which he caught
were dumped into a huge barrel. (But this time he didn’t
pack them on their backs.) And all the creatures stood
around and watched. For this Greedy Person had put
no cover on the barrel. (But this was in the Beginning
of Things.)

He knew Crab Nature, and was not at all worried about
his Crabs. For as soon as any one Crab began to climb
up on the side of the barrel to work his way toward the
top the other Crabs would reach up, grab him by the legs,
and down he would come, kerplunk! “If we can’t get
up,” they would say&mdash;“if we can’t get up, you shan’t get
up, either. We’ll pull you down. Besides, you should
wait until the barrel bursts. There are Kind Friends on
the Outside who will burst, the barrel if we only wait, and
then, when the Great Day dawns, we will all be Emancipated 
and there’ll be no need for Climbing. Come down,
you fool!” (Because this was in the Beginning of Things,
Best Beloved.) So the Greedy Person could always get
as many Crabs as he needed for the Home Market, because 
they all depended on him for their food.

And all the creatures stood around and laughed. For
this was very funny in the Beginning of Things. And all
the creatures said that the Reason for this kink in Crab
Nature was that when the Creator was giving out heads
he didn’t have enough to go around, so the poor Crabs
didn’t get any.

And the Greedy Person thanked his
lucky stars that Crabs had been made in that Peculiar
way, since it made it unnecessary to put a cover on his
barrel or to waste his precious time a-watching of them.
(Now, all this happened long ago, Best Beloved, in the
very Beginning of Things.)

&mdash;

The above is the first of our Just-So Stories&mdash;with no
apologies to Rudyard Kipling or any one else. We print
it here because, just at this time the Crabs are at work in
Harlem, and there is a tremendous clashing of claws as
the Pull ’Em Down program goes forward. It’s a great
game, to be sure, but it doesn’t seem to get them or us anywhere. 
The new day that has dawned for the Negroes of
Harlem is a day of business accomplishment. People are
going into business, saving their money and collectively
putting it into enterprises which will mean roofs over their
heads and an economic future for themselves and their
little ones.

But the Subsidized Sixth are sure that this is all wrong
and that we have no right to move an inch until the Socialist 
millennium dawns, when we will all get “out of the
barrel” together. It does not seem to have occurred to
them that making an imperfect heaven now does not
unfit any one for enjoying the perfect paradise which they
promise us&mdash;if it ever comes. Truly it is said of them 
that “the power over a man’s subsistence is the power over
his will”&mdash;and over his “scientific radicalism,” too. But
we remember having translated this long ago into the less
showy English of “Show me whose bread you eat, and
I’ll tell you whose songs you’ll sing.” Surely this applies
to radicals overnight as well as to ordinary folk. And
if not, why not?

But when the reek of the poison gas propaganda has
cleared away and the smoke of the barrage has lifted it
will be found that “White Men’s Niggers” is a phrase
that need not be restricted to old-line politicians and editors. 
Criticism pungent and insistent is due to every
man in public life and to every movement which bids for
public support. But the cowardly insinuator who from
the safe shelter of nameless charges launches his poisoned
arrows at other people’s reputation is a contemptible
character to have on any side of any movement. He is
generally a liar who fears that he will be called to account
for his lies if he should venture to name his foe. No man
with the truth to tell indulges in this pastime of the
skulker and the skunk. Let us, by all means, have clear,
hard-hitting criticism, but none of this foul filth which
lowers the thing that throws it. In the name of common
sense and common decency, quit being Just Crabs.

</div>